# Konzept der vorliegenden Wirkungskontrolle

Die vorliegende Wirkungskontrolle entspricht einer Synthese zwischen der Attraktivitätskontrolle ausgewählter Lebensraumaufwertungen und ergänzenden Datensätzen von Wiesel &amp; Co am Zimmerberg. Folgende Hintergründe erklären die Wahl des gewählten Konzepts:

Gemäss dem Konzept von Müri und Weinberger (2013) besteht die Erfolgskontrolle aus der Umsetzungskontrolle, der Attraktivitätskontrolle sowie der Populationskontrolle. Diese Bestandteile können auch als drei unterschiedliche Ansätze verstanden werden, um den Erfolg eines Aufwertungsprojektes zu messen, und unterscheiden sich stark in ihrem Aufwand und ihrer Aussagekraft.

Die **Umsetzungskontrolle** stellt die einfachste Art dar, den Erfolg des Projektes zu messen. Dabei gilt es die Anzahl der realisierten Massnahmen bzw. deren Anteil an den geplanten Massnahmen zu bestimmen. Dieser Kennwert (z.B. "80% aller geplanten Massnahmen konnten umgesetzt werden") sagt jedoch wenig darüber aus, ob die umgesetzten Massnahmen auch zum gewünschten Erfolg (Stärkung der lokalen Wieselpopulation) beitragen. Werden Massnahmen ungünstig angelegt, sind sie für die Zielarten nicht nutzbar. Die Umsetzungskontrolle erfolgt in den Berichterstattungen, welche einsehbar sind unter: [wieselundco.ch/projekt/resultate](http://www.wieselundco.ch/projekt/resultate).

Am aufwändigsten ist die **Populationskontrolle** : Hier wird untersucht, ob sich die Population durch die umgesetzten Massnahmen günstig entwickelt hat. Eine solche Untersuchung hat die grösste Aussagekraft, da sie direkt die Kernfrage beantwortet. Jedoch unterliegen Hermelin- und Mauswieselpopulationen starken Schwankungen, die von externen Faktoren wie Witterung und Nahrungsverfügbarkeit abhängig sind. Um eine fundierte Aussage über die projektbedingte Populationsentwicklung machen zu können, wären Langzeitstudien vor und nach der Umsetzung nötig, was finanziell und logistisch einen unverhältnismässig hohen Aufwand bedeuten würde.

Bei der **Attraktivitätskontrolle** handelt es sich um einen Kompromiss zwischen Machbarkeit und Aussagekraft. Diese fokussiert auf die Frage, ob und wie häufig die erstellten Strukturen von den Zielarten genutzt wurden. Sie hat eine erheblich grössere Aussagekraft als diejenige der Umsetzungskontrolle, weil die Nutzung der Strukturen mitberücksichtigt wird. Die vorliegende Untersuchung verfolgt diesen Ansatz ("Attraktivitätskontrolle"). Dazu wurden zwei Erhebungen durchgeführt: Zum einen wurden **Asthaufen mit Spurentunnel** , zum anderen **Winterquartiere mit Fotofallen** beobachtet.

Die Resultate der Spurentunnel und Fotofallen geben nicht nur Aufschluss darüber, wie viele sondern auch welche Strukturen wie oft (und von welchen Arten) besucht wurden. Eine Erhebung verschiedener Parameter von sehr gut und sehr schlecht frequentierten Asthaufen soll Aufschlüsse über die Faktoren geben, was Strukturen für Wiesel & Co attraktiv machen. 

Zusätzlich werden zwei weitere Datensätze von Seite Wiesel &amp; Co am Zimmerberg beigezogen: Zum einen handelt es sich um Daten von spontan und unsystematisch durchgeführten Spurentunnel Erhebungen und zum anderen um Sichtungsmeldungen aus der Bevölkerung. Weitere Details dazu im nächsten Kapitel "Methode".
