# Literaturverzeichnis


Blant, M. (2019): Biodiversite et rongeurs module 2: Suivi des populations de petits carnivores, paysage diversifié versus paysage pauvre - Rapport final novembre 2019. Unveröffentlichter Projektbericht.

Boschi, C und Krummenacher, J (2018): Fördermassnahmen für Wiesel im Landwirtschaftsgebiet - Ein Ansatz zur Erhaltung der Biodiversität und zur Reduktion von Wühlmausschäden im Wiesland. WIN Wieselnetz und Agrofutura (Hrsg.) ([download](http://wieselnetz.ch/wp-content/uploads/2018/02/Heft_Wieselfoerdermassnahmen_D_Ed2_CMYK.pdf))

Capt, S. und Marchesi, P. (2010): Rapport du projet pilote 2009 - Koordination des Pilotprojets und der Vorbereitungen zu einem schweizweiten Musteliden Monitoring (Mustela nivalis, Mustela erminea, Mustela putorius) (unveröffentlicht)

Capt, S. und Marchesi, P. (2012): Monitoring der Kleinmusteliden in der Schweiz – Resultate der Erhebung 2010, Centre Suisse de Cartographie de la Faune (CSCF), Neuchâtel ([download](http://wieselnetz.ch/wp-content/uploads/2016/03/CSCF_Bericht_Monitoring_2010.pdf))

Dürst, A. C. und Vogler, H. (2019): Zustandsaufnahme der Kleinmustelidenfauna im Gebiet Wauwilermoos. Erhebung 2018 und Methodenvergleich. Landwirtschaft und Wald, Luzern ([download](https://lawa.lu.ch/-/media/LAWA/Dokumente/njf/jagd/wildhut/BE_Kleinmusteliden.pdf?la=de-CH&amp;hash=36F5693ABEA00418BC192264A90DDDC4D95D10A0))

Engler, D. (2013): Untersuchung der Nutzung unterschiedliche strukturierter Lebensräume durch Kleinmusteliden und Schläfer. Bachelorarbeit an der Zürcher Hochschule für Angewandte Wissenschaften (ZHAW), Wädenswil (unveröffentlicht)

King, C. M und Edgar, R. L. (1977): Techniques for trapping and tracking stoats (_Mustela erminea_); a review, and a new system, New Zealand Journal of Zoology, 4(2): 193-212

Laas, I. (2017): Validierung eines Habitatmodells für das Hermelin (Mustela erminea) in der Region Zimmerberg. Semesterarbeit an der Zürcher Hochschule für Angewandte Wissenschafte (ZHAW), Wädenswil (unveröffentlicht)

Müri, H. und Weinberger, I. (2013): Konzept Erfolgskontrolle Umsetzungskontrolle – Attraktivitätskontrolle – Populationskontrolle. WIN Wieselnetz - Erfolgskontrolle Wiesellandschaft (unveröffentlicht)

Müri, H. und Weinberger, I. (2015): Wiesellandschaft Schweiz: Erfolgskontrolle für intensive Wieselförderprojekte Kurzfassung für Projektleiter. WIN Wieselnetz - Erfolgskontrolle Wiesellandschaft (unveröffentlicht)

Steffen (2018) Erfolgskontrolle Wieselburgen 2018. Projektbericht (unveröffentlicht)

Steffen, F. (2020): Nachweiswahrscheinlichkeit von Hermelinen (Mustela erminea) mittels Spurentunnel. Bachelorarbeit. Zürcher Hochschule für Angewandte Wissenschaften ZHAW, Wädenswil (noch nicht veröffentlicht)

Ratnaweera, N. (2015): Lebensraumanalyse für Hermelin (_Mustela erminea_), Mauswiesel (_Mustela nivalis_) und Iltis (_Mustela putorius_) am Zimmerberg. Projektarbeit. Zürcher Hochschule für Angewandte Wissenschaften ZHAW, Wädenswil

Ratnaweera, N., Sigrist, B., Graf, R. (2020): Wieselfördermassnahmen in intensiven Obstkulturen in der Region Martigny VS - Erfolgskontrolle mittels Spurentunnel und Fotofallenboxen. Projektbericht. Zürcher Hochschule für Angewandte Wissenschaften ZHAW, Wädenswil (nicht veröffentlicht)